In [33]:
import numpy as np 

class Prova:
    ket_0=np.array([1,0])
    ket_1=np.array([0,1])
    H = (1 / np.sqrt(2)) * np.array([[1, 1],
                                 [1, -1]])
    I=np.array([[1,0],
            [0,1]])
    X=np.array([[0,1],
            [1,0]])
    Y=np.array([[0, 0 -1j],
            [0 +1j, 0]])
    Z=np.array([[1,0],
            [0,-1]])

    @staticmethod
    def tconj(a):
        return a.T.conj()
    @staticmethod
    def tensor(a,b):
        return np.kron(a,b)
    @staticmethod
    def times(a,b):
        return a@b
    @staticmethod
    def inpro(a,b):
        return np.dot(a,b)
    @staticmethod
    def outpro(a,b):
        return np.outer(a,b)

In [71]:
print(Prova.tconj(Prova.ket_0))
print(Prova.tensor(Prova.I, Prova.ket_0))
print(Prova.times(Prova.ket_0,Prova.ket_1))
print(Prova.inpro(Prova.ket_1,Prova.ket_0))
print(Prova.outpro(Prova.ket_0,Prova.ket_1))

[1 0]
[[1 0 0 0]
 [0 0 1 0]]
0
0
[[0 1]
 [0 0]]


|ψ⟩ = (<1|1>) ⊗(H.X|1⟩)

In [72]:
 
def resolucao():
    resultado_X = Prova.inpro(Prova.X, Prova.ket_1)

    resultado_H = Prova.inpro(Prova.H, resultado_X)

    ket2=Prova.inpro(Prova.ket_1, Prova.tconj( Prova.ket_1))

    tensor = Prova.tensor(ket2, resultado_H)
    
    return tensor.reshape(-1, 1)

print(resolucao())


[[0.70710678]
 [0.70710678]]
