In [1]:
import numpy as np

In [91]:
class quantum:
    ket_0 =  np.array([1,0])
    ket_1 =  np.array([0,1])
    h = (1 / np.sqrt(2))* np.array([[1,1],[1,-1]])
    x = np.array([[0,1],[1,0]])
    y= np.array([[0,-1j],[1j,0]])
    z = np.array([[1,0],[0,-1]])
    i = np.eye(2)
    @staticmethod
    def tconj(a):
        matriz = np.array(a)
        matriz_transposta = np.transpose(matriz)
        matriz_conj = matriz_transposta.conjugate()
        return matriz_conj
    @staticmethod
    def tensor(a,b):
        m1=np.array(a)
        m2=np.array(b)
        produto_tensorial = np.kron(m1,m2)
        return produto_tensorial
    @staticmethod
    def times(a,b):
        m1 = np.array(a)
        m2 = np.array(b)
        matriz_multi = m1 @ m2
        return matriz_multi
    @staticmethod
    def inpro(a,b):
        m2= np.array(b)
        produto_interno = np.dot(quantum.tconj(a),m2)
        return produto_interno
    @staticmethod
    def outpro(a,b):
        m1 = np.array(a)
        m2 = np.array(b)
        produto_externo = np.outer(m1,m2)
        return produto_externo
    

In [92]:
def resolucao():
        pauli_x_1 = quantum.times(quantum.x,quantum.ket_1)
        print(f"pauli_x_1 {pauli_x_1}")
        hadamard_x_1 = quantum.times(quantum.h,pauli_x_1)
        print(f"hadamard_x_1 {hadamard_x_1}")
        prod_interno_1_1 = quantum.inpro(quantum.ket_1,quantum.ket_1)
        print(f"prod_interno_1_1 {prod_interno_1_1}")
        resultado = quantum.tensor(prod_interno_1_1,hadamard_x_1)
        print(f"resultado {resultado}")
        return resultado

In [93]:
resolucao()

pauli_x_1 [1 0]
hadamard_x_1 [0.70710678 0.70710678]
prod_interno_1_1 1
resultado [0.70710678 0.70710678]


array([0.70710678, 0.70710678])

In [32]:
quantum.inpro(quantum.ket_0,quantum.h)

array([0.70710678, 0.70710678])

In [21]:
quantum.times([[1],[2],[3]],[[3,2,1]])

array([[3, 2, 1],
       [6, 4, 2],
       [9, 6, 3]])

In [10]:
quantum.tensor([1,2,3],[1,2,3])

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [28]:
quantum.tconj([[-1j,2,3],[3j,-2j,1]])

array([[-0.+1.j,  0.-3.j],
       [ 2.-0.j, -0.+2.j],
       [ 3.-0.j,  1.-0.j]])